config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'questions#index'

  resources :questions do
    collection do
      get :try_to_answer
      get :get_answer
    end
  end

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :content, :answer, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :try_to_answer, :get_answer]

  def index
    @questions = Question.all.order('id asc')
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = 'Question created'
      redirect_to questions_path
    else
      flash[:error] = @question.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes(question_params)
      flash[:notice] = 'Question updated'
      redirect_to questions_path
    else
      flash[:error] = @question.errors.full_messages.join(', ')
      render :edit
    end
  end

  def show
  end

  def destroy
    if @question.destroy
      flash[:notice] = "Question deleted"
    else
      flash[:error] = @question.errors.full_messages.join(', ')
    end
    redirect_to questions_path
  end

  def try_to_answer
  end

  def get_answer
    # @result = @question.check_answer(params[:user_answer])
    @result = AnswerAlgorithm.new.run(@question.answer, params[:user_answer])

    respond_to do |format|
      format.js { render :get_answer}
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :content, :answer)
    end

    def set_question
      @question = Question.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Quiz Master", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">
  <%= bootstrap_flash %>
  <%= yield %>
  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Quiz Master 2016</p>
      </div>
    </div>
    <!-- /.row -->
  </footer>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <label class="col-sm-2 control-label">Title</label>
    <div class="col-sm-7">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Content</label>
    <div class="col-sm-7">
    <%= cktext_area :question, :content, cols: 40, ckeditor: { toolbar: 'mini' }%>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-2 control-label">Answer</label>
    <div class="col-sm-7">
      <%= f.text_field :answer, class: 'form-control', placeholder: 'Answer' %>
    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to 'Cancel', questions_path, class: 'btn btn-default' %>
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
<% end %>

app/views/questions/_reload_answer.html.erb
<%= html.html_safe %>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>
<%= render 'form' %>

app/views/questions/get_answer.js.erb
$("#user_answer").html("<%= j(render('reload_answer', :html => @result)) %>");

app/views/questions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Questions
      <small><%= link_to "Add New", new_question_path, class: 'btn btn-default' %></small>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% if @questions.blank? %>
          <tr class="blank-slate">
            <td colspan="8">
              <p>No Data<br/>Please add new question</p>
            </td>
          </tr>
        <% end %>
        <% @questions.each do |question| %>
          <tr>
            <td><%= question.title %></td>
            <td>
              <%= link_to question do %>
                <%= glyph "info-sign" %>
              <% end %>
              <%= link_to edit_question_path(question) do %>
                <%= glyph "pencil" %>
              <% end %>
              <%= link_to question_path(question), :method => :delete, :data => { :confirm => "Are you sure?" }, :title => "Delete" do %>
                <%= glyph "remove" %>
              <%- end -%>
              <%= link_to "Answer", try_to_answer_questions_path(id: question.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<hr>

app/views/questions/new.html.erb
<h2>New Question</h2>
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Show Question <%=  @question.title %></h1>
  </div>
</div>

<div class="row">  
  <div class="col-lg-1">
    Question:
  </div>
  <div class="col-lg-5">
    <%= @question.content.html_safe %>
  </div>
</div>

<div class="row">  
  <div class="col-lg-1">
    Answer:
  </div>
  <div class="col-lg-5">
    <%= @question.answer %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= link_to 'Back', questions_path, class: 'btn btn-default pull-right' %>
  </div>
</div>

app/views/questions/try_to_answer.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Answer Question <%=  @question.title %></h1>
  </div>
</div>

<div class="row">  
  <div class="col-lg-1">
    Question:
  </div>
  <div class="col-lg-5">
    <%= @question.content.html_safe %>
  </div>
</div>

<div class="row">  
  <div class="col-lg-1">
    Answer:
  </div>
  <div class="col-lg-5">
    <%= text_field_tag 'answer', '', placeholder: 'your answer', class: 'form-control' %>
    <%= hidden_field_tag 'question_id', @question.id %>
  </div>
</div>

<div class="row">
  <div class="col-lg-5">
    <div id="user_answer"></div>
  </div>
</div>

<script type="text/javascript">
  var timer;

  $("input#answer").on('keyup', function() {
    clearTimeout(timer);  //clear any running timeout on key up
    timer = setTimeout(function() { //then give it a second to see if the user is finished
      $.ajax({
        url: '/questions/get_answer',
        type:'get',
        data: {
          id: $("#question_id").val(),
          user_answer: $("#answer").val()
        },
        success: function( data ) {

        },
        error: function( data ){

        }
      }); 
    }, 500);
  });
</script>